product_homepage:
    path:     /product
    defaults: { _controller: ProductBundle:Default:index }
product_add:
    path:	/product/add
    defaults: { _controller: ProductBundle:Default:add }
product_edit:
    path:     /product/edit/{id}
    defaults: { _controller: ProductBundle:Default:edit }
product_delete:
    path:     /product/delete/{id}
    defaults: { _controller: ProductBundle:Default:delete }
